-- 1. Which products generate the highest total sales revenue?
select* from Sales_SalesOrderHeader;

select* from Sales_SalesOrderDetail;

select* from Production_Product;

select PP.NAME AS PRODUCT_NAME, SUM(SSOH.TotalDue) AS Total_salesrevenue
from production_product PP
inner join sales_salesorderdetail SSOD
ON PP.ProductID = SSOD.ProductID
LEFT JOIN Sales_SalesOrderHeader SSOH
ON SSOH.SalesOrderID = SSOD.SalesOrderID
GROUP BY PRODUCT_NAME
order by Total_salesrevenue desc;

-- 2. What is the total revenue generated by each sales territory?
select* from Sales_SalesOrderHeader;

select* from Sales_SalesOrderDetail;

select* from Sales_SalesTerritory;

select SST.NAME AS Territory_NAME, SUM(SSOH.TotalDue) AS Total_salesrevenue
from  Sales_SalesTerritory SST
inner join Sales_SalesOrderHeader SSOH
ON SST.TerritoryID = SSOH.TerritoryID
LEFT JOIN sales_salesorderdetail SSOD
ON SSOD.SalesOrderID = SSOH.SalesOrderID 
GROUP BY  Territory_NAME
order by Total_salesrevenue desc;

-- 3. Which vendors supply products that are actively being sold?
SELECT * FROM Purchasing_Vendor;

SELECT * FROM Purchasing_ProductVendor;

SELECT * FROM Production_Product;

SELECT * FROM Sales_SalesOrderDetail;

SELECT PV.Name AS VENDOR_NAME, PP.NAME AS PRODUCT_NAME, COUNT(SSOD.OrderQty) AS COUNT_VENDORSALE
FROM PURCHASING_VENDOR  PV
INNER JOIN Purchasing_ProductVendor PPV
ON PV.BusinessEntityID =PPV.BusinessEntityID
INNER JOIN  PRODUCTION_PRODUCT PP
ON PP.ProductID = PPV.ProductID
INNER JOIN SALES_SALESORDERDETAIL SSOD
ON SSOD.ProductID =PP.ProductID
GROUP BY VENDOR_NAME, PRODUCT_NAME
ORDER BY COUNT_VENDORSALE DESC

-- 4. What is the average standard production cost by product category?
SELECT * FROM Production_Product;

SELECT * FROM Production_ProductSubcategory;

SELECT * FROM Production_ProductCategory;

SELECT PPC.NAME AS Category, avg(PP.StandardCost) as Average_Productcost
from production_product PP
inner join production_productsubcategory PPS
ON PP.ProductSubcategoryID = PPS.ProductSubcategoryID
inner join production_productcategory PPC
ON PPC.ProductCategoryID = PPS.ProductCategoryID
group by PPC.NAME
Order by Average_Productcost;

-- 5. Which customers contribute the highest production demand (by quantity ordered)?
select * from Sales_Customer;

select * from Sales_SalesOrderHeader;

select * from Sales_SalesOrderDetail;

select * from person_person;

select CONCAT(PP.FirstName, " ", PP.LastName) AS CUSTOMERNAME, sum(SSOD.OrderQty) AS NUMBEROFORDERS
from person_person PP
LEFT JOIN sales_customer SC
ON PP.BusinessEntityID = SC.CustomerID
RIGHT JOIN sales_salesorderheader SSOH
ON SSOH.CustomerID = SC.CustomerID
INNER JOIN  sales_salesorderdetail SSOD
ON SSOD.SalesOrderID = SSOH.SalesOrderID
GROUP BY CUSTOMERNAME
ORDER BY NUMBEROFORDERS DESC

-- 6. What is the total inventory quantity available per location?

select * from Production_ProductInventory;

select * from Production_Location;

select * from Production_Product;
SELECT PPI.LocationID LOCATION_NUMBER, PL.NAME LOCATION, SUM(PPI.Quantity) INVENTORYQUANTITY
FROM production_productinventory PPI
INNER JOIN production_location PL
ON PPI.LocationID = PL.LocationID
GROUP BY LOCATION_NUMBER, LOCATION
ORDER BY SUM(PPI.Quantity) DESC

-- 7. Which shipping methods generate the highest revenue?
SELECT * FROM Sales_SalesOrderHeader;

SELECT * FROM Purchasing_ShipMethod;
SELECT SM.Name AS ShipMethod, SUM(SOH.TotalDue) AS TotalRevenue
FROM Sales_SalesOrderHeader SOH
INNER JOIN Purchasing_ShipMethod SM 
ON SOH.ShipMethodID = SM.ShipMethodID
GROUP BY SM.Name
ORDER BY TotalRevenue DESC;

-- 8. What is the total sales performance of each sales representative?
SELECT* FROM Sales_SalesPerson;

SELECT* FROM Sales_SalesOrderHeader;

SELECT SP.BusinessEntityID, SUM(SOH.TotalDue) AS TotalSales
FROM Sales_SalesPerson SP
INNER JOIN Sales_SalesOrderHeader SOH
ON SP.BusinessEntityID = SOH.SalesPersonID
GROUP BY SP.BusinessEntityID
ORDER BY TotalSales DESC;

-- 9. What is the total revenue generated by each product line?
SELECT * FROM Production_Product;

SELECT * FROM Sales_SalesOrderDetail;

SELECT PP.ProductLine, SUM(SSOD.LineTotal) AS TotalRevenue
FROM Production_Product PP
INNER JOIN Sales_SalesOrderDetail SSOD
ON PP.ProductID = SSOD.ProductID
GROUP BY PP.ProductLine
ORDER BY TotalRevenue DESC;

-- 10. Which products have a standard cost above the company average?

SELECT ProductID,Name,StandardCost
FROM Production_Product
WHERE StandardCost >
(SELECT AVG(StandardCost)
    FROM Production_Product);
    
-- 11. Which customers have total purchases greater than the average customer spending?
SELECT c.CustomerID,SUM(soh.TotalDue) AS TotalSpent
FROM Sales_Customer c
INNER JOIN Sales_SalesOrderHeader SOH
ON C.CustomerID = SOH.CustomerID
GROUP BY C.CustomerID
HAVING SUM(SOH.TotalDue) >
(SELECT AVG(TotalDue)
FROM Sales_SalesOrderHeader);

-- 12. Which products have never been sold?
select* FROM Production_Product;

select* FROM Sales_SalesOrderDetail;

SELECT ProductID, Name
FROM Production_Product
WHERE ProductID NOT IN
(SELECT DISTINCT ProductID
FROM Sales_SalesOrderDetail);

-- 13. Customers Purchasing Most Product Categories?
SELECT * FROM Sales_SalesOrderHeader SSOH;

SELECT * FROM Sales_SalesOrderDetail SSOD;

SELECT * FROM Production_Product;

SELECT SC.CustomerID, COUNT(DISTINCT PC.ProductCategoryID) AS CategoryCount
FROM Sales_SalesOrderHeader SSOH
JOIN Sales_SalesOrderDetail SSOD 
ON SSOH.SalesOrderID = SSOD.SalesOrderID
JOIN Production_Product PP
ON SSOD.ProductID = PP.ProductID
JOIN Production_ProductSubcategory PS 
ON PP.ProductSubcategoryID = PS.ProductSubcategoryID
JOIN Production_ProductCategory PC 
ON PS.ProductCategoryID = PC.ProductCategoryID
JOIN Sales_Customer SC
ON SSOH.CustomerID = SC.CustomerID
GROUP BY SC.CustomerID
ORDER BY CategoryCount DESC;

-- 14. What is the Best Performing Category per Territory?

SELECT SST.Name AS Territory,PC.Name AS Category,SUM(SSOD.LineTotal) AS Revenue
FROM Sales_SalesOrderHeader SSOH
JOIN Sales_SalesOrderDetail SSOD
ON SSOH.SalesOrderID = SSOD.SalesOrderID
JOIN Production_Product PP
ON SSOD.ProductID = PP.ProductID
JOIN Production_ProductSubcategory PPS 
ON PP.ProductSubcategoryID = PPS.ProductSubcategoryID
JOIN Production_ProductCategory PC
ON PPS.ProductCategoryID = PC.ProductCategoryID
JOIN Sales_SalesTerritory SST
ON SSOH.TerritoryID = SST.TerritoryID
GROUP BY SST.Name, PC.Name
ORDER BY Revenue DESC;

-- 15. Which vendors supply products with the highest rejection rates?

SELECT PV.Name,avg(POD.RejectedQty * 1.0 / POD.OrderQty) AS RejectionRate
FROM Purchasing_PurchaseOrderDetail POD
JOIN Purchasing_PurchaseOrderHeader POH
ON POD.PurchaseOrderID = POH.PurchaseOrderID
JOIN Purchasing_Vendor PV
ON POH.VendorID = PV.BusinessEntityID
GROUP BY PV.Name
ORDER BY RejectionRate DESC;





